# Spring boot application
dubbo.application.name=dubbo-auto-configuration-provider-inventory
# Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
dubbo.scan.base-packages=inventory
# Dubbo Application
## The default value of dubbo.application.name is ${spring.application.name}
## dubbo.application.name=${spring.application.name}
# Dubbo Protocol
dubbo.protocol.name=dubbo
dubbo.protocol.port=12345
## Dubbo Registry
dubbo.registry.address=N/A
spring.jersey.application-path=transactions
server.port=9091
spring.jta.atomikos.properties.log-base-name=inventory