<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.atomikos</groupId>
		<artifactId>transactions-essentials</artifactId>
		<version>5.0.10-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>osgi-example-db</artifactId>
	<dependencies>

		<dependency>
			<groupId>com.atomikos</groupId>
			<artifactId>transactions-osgi</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.derby</groupId>
			<artifactId>derby</artifactId>
			<version>10.8.1.2</version>
		</dependency>

		<dependency>
			<groupId>com.atomikos</groupId>
			<artifactId>transactions-jdbc</artifactId>
			<scope>provided</scope>
		</dependency>
	</dependencies>
</project>