
package com.atomikos.icatch.jaxb.wsat.v200410;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:41:09 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebService(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", name = "CoordinatorPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface CoordinatorPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "CommittedOperation")
    public void committedOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Committed")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "PreparedOperation")
    public void preparedOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Prepared")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "AbortedOperation")
    public void abortedOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Aborted")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "ReplayOperation")
    public void replayOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Replay")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "ReadOnlyOperation")
    public void readOnlyOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "ReadOnly")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );
}
