
package com.atomikos.icatch.jaxb.wsat.v200410;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:41:09 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebService(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", name = "ParticipantPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface ParticipantPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "RollbackOperation")
    public void rollbackOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Rollback")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "CommitOperation")
    public void commitOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Commit")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "PrepareOperation")
    public void prepareOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wsat", partName = "parameters", name = "Prepare")
        com.atomikos.icatch.jaxb.wsat.v200410.Notification parameters
    );
}
