
package com.atomikos.icatch.jaxb.atomikos.v200510;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;
import javax.jws.Oneway;
import javax.jws.WebMethod;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:38:06 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebService(targetNamespace = "http://www.atomikos.com/schemas/2005/10/transactions", name = "CoordinatorPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface CoordinatorPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod
    public void participantErrorNotification(
        @WebParam(targetNamespace = "http://www.atomikos.com/schemas/2005/10/transactions", partName = "ErrorContent", name = "Error")
        com.atomikos.icatch.jaxb.atomikos.v200510.ErrorMessageType errorContent
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod
    public void prepared(
        @WebParam(targetNamespace = "http://www.atomikos.com/schemas/2005/10/transactions", partName = "PrepareResponseContent", name = "Prepared")
        com.atomikos.icatch.jaxb.atomikos.v200510.PreparedMessageType prepareResponseContent
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod
    public void participantStateNotification(
        @WebParam(targetNamespace = "http://www.atomikos.com/schemas/2005/10/transactions", partName = "StateContent", name = "State")
        com.atomikos.icatch.jaxb.atomikos.v200510.StateMessageType stateContent
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod
    public void replayCompletion(
        @WebParam(targetNamespace = "http://www.atomikos.com/schemas/2005/10/transactions", partName = "ReplayContent", name = "Replay")
        com.atomikos.icatch.jaxb.atomikos.v200510.TransactionMessageType replayContent
    );
}
