
package com.atomikos.icatch.jaxb.wsc.v200410;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:40:00 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebService(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", name = "RegistrationRequesterPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface RegistrationRequesterPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "RegisterResponseOperation")
    public void registerResponseOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", partName = "parameters", name = "RegisterResponse")
        com.atomikos.icatch.jaxb.wsc.v200410.RegisterResponseType parameters
    );
}
