
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.atomikos.icatch.jaxb.wsc.v200410;

import java.util.logging.Logger;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:39:56 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@javax.jws.WebService(name = "ActivationCoordinatorPortType", serviceName = "ActivationService",
                      portName = "ActivationCoordinatorPort",
                      targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", 
                      wsdlLocation = "file:./resources/wsdl/wst/v200410/wscoor.wsdl" ,
		      endpointInterface = "com.atomikos.icatch.jaxb.wsc.v200410.ActivationCoordinatorPortType")
                      
public class ActivationCoordinatorPortTypeImpl implements ActivationCoordinatorPortType {

    private static final Logger LOG = 
        Logger.getLogger(ActivationCoordinatorPortTypeImpl.class.getPackage().getName());

    /* (non-Javadoc)
     * @see com.atomikos.icatch.jaxb.wsc.v200410.ActivationCoordinatorPortType#createCoordinationContextOperation(com.atomikos.icatch.jaxb.wsc.v200410.CreateCoordinationContextType  parameters )*
     */
    public void createCoordinationContextOperation(
        com.atomikos.icatch.jaxb.wsc.v200410.CreateCoordinationContextType parameters
    )
    { 
       LOG.info("Executing operation createCoordinationContextOperation");
    }

}
