
package com.atomikos.icatch.jaxb.wsc.v200410;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:40:00 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebServiceClient(name = "FaultService", targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", wsdlLocation = "file:./resources/wsdl/wst/v200410/wscoor.wsdl")
public class FaultService extends Service {

    private final static URL WSDL_LOCATION;
    private final static QName SERVICE = new QName("http://schemas.xmlsoap.org/ws/2004/10/wscoor", "FaultService");
    private final static QName FaultPort = new QName("http://schemas.xmlsoap.org/ws/2004/10/wscoor", "FaultPort");
    static {
        URL url = null;
        try {
            url = new URL("file:./resources/wsdl/wst/v200410/wscoor.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:./resources/wsdl/wst/v200410/wscoor.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FaultService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaultService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns FaultPort
     */
    @WebEndpoint(name = "FaultPort")
    public FaultPortType getFaultPort() {
        return (FaultPortType)super.getPort(FaultPort, FaultPortType.class);
    }

}
