
package com.atomikos.icatch.jaxb.wsc.v200410;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the CXF 2.0-incubator
 * Wed Jul 11 17:39:59 CEST 2007
 * Generated source version: 2.0-incubator
 * 
 */

@WebService(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", name = "RegistrationCoordinatorPortType")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface RegistrationCoordinatorPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Oneway
    @WebMethod(operationName = "RegisterOperation")
    public void registerOperation(
        @WebParam(targetNamespace = "http://schemas.xmlsoap.org/ws/2004/10/wscoor", partName = "parameters", name = "Register")
        com.atomikos.icatch.jaxb.wsc.v200410.RegisterType parameters
    );
}
